### ISSUE TITLE
Error: Cannot find module 'node:process'

### ISSUE THREAD

**Issue by schreinermark** [b5i/apple-playlist-downloader-cli#4]
I've installed via "npm i -g apple-playlist-downloader" and get the following error which looks a bit different that the other open issue:
(This is a fresh and up-to-date install of NPM and nothing else is running on the machine)

root@*:/home/*/AppleMusicDL# apd ****playlist*****
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:process'
Require stack:
- /usr/local/lib/node_modules/apple-playlist-downloader/bin/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/apple-playlist-downloader/bin/app.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/apple-playlist-downloader/bin/app.js'
  ]
}

**Comment by b5i** [comment]
> I've installed via "npm i -g apple-playlist-downloader" and get the following error which looks a bit different that the other open issue:
> 
> (This is a fresh and up-to-date install of NPM and nothing else is running on the machine)
> 
> 
> 
> root@*:/home/*/AppleMusicDL# apd ****playlist*****
> 
> internal/modules/cjs/loader.js:818
> 
>   throw err;
> 
>   ^
> 
> 
> 
> Error: Cannot find module 'node:process'
> 
> Require stack:
> 
> - /usr/local/lib/node_modules/apple-playlist-downloader/bin/app.js
> 
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
> 
>     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
> 
>     at Module.require (internal/modules/cjs/loader.js:887:19)
> 
>     at require (internal/modules/cjs/helpers.js:74:18)
> 
>     at Object.<anonymous> (/usr/local/lib/node_modules/apple-playlist-downloader/bin/app.js:2:17)
> 
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
> 
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> 
>     at Module.load (internal/modules/cjs/loader.js:863:32)
> 
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> 
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
> 
>   code: 'MODULE_NOT_FOUND',
> 
>   requireStack: [
> 
>     '/usr/local/lib/node_modules/apple-playlist-downloader/bin/app.js'
> 
>   ]
> 
> }

What is your node version?

**Comment by schreinermark** [comment]
Node v12.22.5
And now I see that's really old. I'll attempt to update outside of apt.

**Comment by schreinermark** [comment]
Updated to node 19 fixed it. Thanks.
